"""add sprint 8b rca evidence report feedback models

Revision ID: 588e4ea72ee4
Revises: 7a2aae75fdfd
Create Date: 2026-07-25 18:28:10.474312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '588e4ea72ee4'
down_revision: Union[str, Sequence[str], None] = '7a2aae75fdfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COLLECTING', 'COMPLETED', 'PARTIAL', 'FAILED', name='evidence_collection_status'), server_default='PENDING', nullable=False),
    sa.Column('schema_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anchor_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_statuses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collection_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'version', name='uq_incident_evidence_incident_version')
    )
    op.create_index('ix_incident_evidence_incident_created', 'incident_evidence', ['incident_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_incident_evidence_incident_id'), 'incident_evidence', ['incident_id'], unique=False)
    op.create_table('rca_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', name='rca_report_status'), server_default='PENDING', nullable=False),
    sa.Column('schema_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='rca_confidence'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('probable_root_cause', sa.Text(), nullable=True),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contradictory_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alternative_hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['incident_evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'version', name='uq_rca_reports_incident_version')
    )
    op.create_index(op.f('ix_rca_reports_evidence_id'), 'rca_reports', ['evidence_id'], unique=False)
    op.create_index('ix_rca_reports_incident_created', 'rca_reports', ['incident_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_rca_reports_incident_id'), 'rca_reports', ['incident_id'], unique=False)
    op.create_table('rca_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Enum('CORRECT', 'PARTIALLY_CORRECT', 'INCORRECT', name='rca_feedback_rating'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('correct_root_cause', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['rca_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rca_feedback_incident_id'), 'rca_feedback', ['incident_id'], unique=False)
    op.create_index('ix_rca_feedback_report_created', 'rca_feedback', ['report_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_rca_feedback_report_id'), 'rca_feedback', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rca_feedback_report_id'), table_name='rca_feedback')
    op.drop_index('ix_rca_feedback_report_created', table_name='rca_feedback')
    op.drop_index(op.f('ix_rca_feedback_incident_id'), table_name='rca_feedback')
    op.drop_table('rca_feedback')
    op.drop_index(op.f('ix_rca_reports_incident_id'), table_name='rca_reports')
    op.drop_index('ix_rca_reports_incident_created', table_name='rca_reports')
    op.drop_index(op.f('ix_rca_reports_evidence_id'), table_name='rca_reports')
    op.drop_table('rca_reports')
    op.drop_index(op.f('ix_incident_evidence_incident_id'), table_name='incident_evidence')
    op.drop_index('ix_incident_evidence_incident_created', table_name='incident_evidence')
    op.drop_table('incident_evidence')
    # ### end Alembic commands ###
