"""align event record and dead letter schemas

Revision ID: 9b9bb1e4597e
Revises: a2bc0b517200
Create Date: 2026-06-28 09:05:58.488932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b9bb1e4597e'
down_revision: Union[str, Sequence[str], None] = 'a2bc0b517200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dead_letter_events', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('dead_letter_events', sa.Column('raw_event', sa.JSON(), nullable=True))
    op.add_column('dead_letter_events', sa.Column('error_reason', sa.Text(), nullable=False))
    op.add_column('dead_letter_events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('dead_letter_events', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dead_letter_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.drop_index(op.f('ix_dead_letter_events_original_topic'), table_name='dead_letter_events')
    op.drop_index(op.f('ix_dead_letter_events_event_id'), table_name='dead_letter_events')
    op.create_index(op.f('ix_dead_letter_events_event_id'), 'dead_letter_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_dead_letter_events_topic'), 'dead_letter_events', ['topic'], unique=False)
    op.drop_column('dead_letter_events', 'original_topic')
    op.drop_column('dead_letter_events', 'failure_reason')
    op.add_column('event_records', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('event_records', sa.Column('raw_event', sa.JSON(), nullable=False))
    op.add_column('event_records', sa.Column('processing_error', sa.Text(), nullable=True))
    op.alter_column('event_records', 'schema_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event_records', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_index(op.f('ix_event_records_processing_status'), 'event_records', ['processing_status'], unique=False)
    op.create_index('ix_event_records_release_timeline', 'event_records', ['correlation_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_event_records_timestamp'), 'event_records', ['timestamp'], unique=False)
    op.drop_column('event_records', 'received_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_records', sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_event_records_timestamp'), table_name='event_records')
    op.drop_index('ix_event_records_release_timeline', table_name='event_records')
    op.drop_index(op.f('ix_event_records_processing_status'), table_name='event_records')
    op.alter_column('event_records', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('event_records', 'schema_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('event_records', 'processing_error')
    op.drop_column('event_records', 'raw_event')
    op.drop_column('event_records', 'timestamp')
    op.add_column('dead_letter_events', sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('dead_letter_events', sa.Column('original_topic', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_dead_letter_events_topic'), table_name='dead_letter_events')
    op.drop_index(op.f('ix_dead_letter_events_event_id'), table_name='dead_letter_events')
    op.create_index(op.f('ix_dead_letter_events_event_id'), 'dead_letter_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_events_original_topic'), 'dead_letter_events', ['original_topic'], unique=False)
    op.alter_column('dead_letter_events', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('dead_letter_events', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('dead_letter_events', 'updated_at')
    op.drop_column('dead_letter_events', 'error_reason')
    op.drop_column('dead_letter_events', 'raw_event')
    op.drop_column('dead_letter_events', 'topic')
    # ### end Alembic commands ###
