SCHEMA_VERSION = "1.0"

# Kafka topics
TOPIC_PIPELINE_EVENTS = "pipeline.events"
TOPIC_DEPLOYMENT_EVENTS = "deployment.events"
TOPIC_KUBERNETES_EVENTS = "kubernetes.events"
TOPIC_TELEMETRY_ALERTS = "telemetry.alerts"
TOPIC_INCIDENT_EVENTS = "incident.events"
TOPIC_REMEDIATION_EVENTS = "remediation.events"
TOPIC_REMEDIATION_COMMANDS = "remediation.commands"
TOPIC_REMEDIATION_RESULTS = "remediation.results"
TOPIC_AUDIT_EVENTS = "audit.events"
TOPIC_DEAD_LETTER_EVENTS = "dead-letter.events"
TOPIC_CHAOS_EVENTS = "platformiq.chaos.events"
TOPIC_CHAOS_RESULTS = "platformiq.chaos.results"


# Pipeline events
PIPELINE_STARTED = "PIPELINE_STARTED"
PIPELINE_COMPLETED = "PIPELINE_COMPLETED"
PIPELINE_FAILED = "PIPELINE_FAILED"
PIPELINE_RISK_CALCULATED = "PIPELINE_RISK_CALCULATED"
PIPELINE_SECURITY_SCAN_COMPLETED = (
    "PIPELINE_SECURITY_SCAN_COMPLETED"
)


# Release / deployment events
RELEASE_APPROVED = "RELEASE_APPROVED"
DEPLOYMENT_STARTED = "DEPLOYMENT_STARTED"
DEPLOYMENT_COMPLETED = "DEPLOYMENT_COMPLETED"
DEPLOYMENT_FAILED = "DEPLOYMENT_FAILED"


# Kubernetes events
KUBERNETES_DEPLOYMENT_HEALTHY = (
    "KUBERNETES_DEPLOYMENT_HEALTHY"
)
KUBERNETES_DEPLOYMENT_UNHEALTHY = (
    "KUBERNETES_DEPLOYMENT_UNHEALTHY"
)
KUBERNETES_POD_UNHEALTHY = (
    "KUBERNETES_POD_UNHEALTHY"
)
KUBERNETES_RESTART_DETECTED = (
    "KUBERNETES_RESTART_DETECTED"
)
KUBERNETES_ROLLOUT_FAILED = (
    "KUBERNETES_ROLLOUT_FAILED"
)


# Observability alert events
HIGH_ERROR_RATE = "HIGH_ERROR_RATE"
HIGH_LATENCY = "HIGH_LATENCY"
POD_RESTART_SPIKE = "POD_RESTART_SPIKE"
SERVICE_DEGRADED = "SERVICE_DEGRADED"
SERVICE_DOWN = "SERVICE_DOWN"


# Reliability alert events
SLO_BREACH = "SLO_BREACH"
AVAILABILITY_BREACH = "AVAILABILITY_BREACH"
LATENCY_BREACH = "LATENCY_BREACH"
ERROR_RATE_BREACH = "ERROR_RATE_BREACH"
ERROR_BUDGET_BURN = "ERROR_BUDGET_BURN"
ERROR_BUDGET_EXHAUSTED = "ERROR_BUDGET_EXHAUSTED"
RELIABILITY_ALERT_CREATED = (
    "RELIABILITY_ALERT_CREATED"
)
ALERT_CREATED = "ALERT_CREATED"


# Audit events
AUDIT_EVENT_CREATED = "AUDIT_EVENT_CREATED"


# Incident events
INCIDENT_CREATED = "INCIDENT_CREATED"
RCA_COMPLETED = "RCA_COMPLETED"


# Chaos experiment events
CHAOS_EXPERIMENT_CREATED = "CHAOS_EXPERIMENT_CREATED"
CHAOS_RUN_STARTED = "CHAOS_RUN_STARTED"
CHAOS_FAULT_INJECTED = "CHAOS_FAULT_INJECTED"
CHAOS_OBSERVATION_RECORDED = "CHAOS_OBSERVATION_RECORDED"
CHAOS_RUN_COMPLETED = "CHAOS_RUN_COMPLETED"
CHAOS_RUN_FAILED = "CHAOS_RUN_FAILED"
CHAOS_RUN_ABORTED = "CHAOS_RUN_ABORTED"
EXPERIMENT_BENCHMARK_CALCULATED = "EXPERIMENT_BENCHMARK_CALCULATED"


# Remediation events
REMEDIATION_RECOMMENDED = "REMEDIATION_RECOMMENDED"
REMEDIATION_APPROVED = "REMEDIATION_APPROVED"
REMEDIATION_REJECTED = "REMEDIATION_REJECTED"
REMEDIATION_COMMAND_CREATED = (
    "REMEDIATION_COMMAND_CREATED"
)
REMEDIATION_COMPLETED = "REMEDIATION_COMPLETED"
REMEDIATION_FAILED = "REMEDIATION_FAILED"
ROLLBACK_STARTED = "ROLLBACK_STARTED"
ROLLBACK_COMPLETED = "ROLLBACK_COMPLETED"
RECOVERY_VERIFIED = "RECOVERY_VERIFIED"
RECOVERY_FAILED = "RECOVERY_FAILED"


EVENT_TOPIC_MAP = {
    # Pipeline events
    PIPELINE_STARTED: TOPIC_PIPELINE_EVENTS,
    PIPELINE_COMPLETED: TOPIC_PIPELINE_EVENTS,
    PIPELINE_FAILED: TOPIC_PIPELINE_EVENTS,
    PIPELINE_RISK_CALCULATED: TOPIC_PIPELINE_EVENTS,
    PIPELINE_SECURITY_SCAN_COMPLETED: (
        TOPIC_PIPELINE_EVENTS
    ),

    # Deployment events
    RELEASE_APPROVED: TOPIC_DEPLOYMENT_EVENTS,
    DEPLOYMENT_STARTED: TOPIC_DEPLOYMENT_EVENTS,
    DEPLOYMENT_COMPLETED: TOPIC_DEPLOYMENT_EVENTS,
    DEPLOYMENT_FAILED: TOPIC_DEPLOYMENT_EVENTS,

    # Kubernetes events
    KUBERNETES_DEPLOYMENT_HEALTHY: (
        TOPIC_KUBERNETES_EVENTS
    ),
    KUBERNETES_DEPLOYMENT_UNHEALTHY: (
        TOPIC_KUBERNETES_EVENTS
    ),
    KUBERNETES_POD_UNHEALTHY: (
        TOPIC_KUBERNETES_EVENTS
    ),
    KUBERNETES_RESTART_DETECTED: (
        TOPIC_KUBERNETES_EVENTS
    ),
    KUBERNETES_ROLLOUT_FAILED: (
        TOPIC_KUBERNETES_EVENTS
    ),

    # Observability alert events
    HIGH_ERROR_RATE: TOPIC_TELEMETRY_ALERTS,
    HIGH_LATENCY: TOPIC_TELEMETRY_ALERTS,
    POD_RESTART_SPIKE: TOPIC_TELEMETRY_ALERTS,
    SERVICE_DEGRADED: TOPIC_TELEMETRY_ALERTS,
    SERVICE_DOWN: TOPIC_TELEMETRY_ALERTS,

    # Reliability alert events
    SLO_BREACH: TOPIC_TELEMETRY_ALERTS,
    AVAILABILITY_BREACH: TOPIC_TELEMETRY_ALERTS,
    LATENCY_BREACH: TOPIC_TELEMETRY_ALERTS,
    ERROR_RATE_BREACH: TOPIC_TELEMETRY_ALERTS,
    ERROR_BUDGET_BURN: TOPIC_TELEMETRY_ALERTS,
    ERROR_BUDGET_EXHAUSTED: TOPIC_TELEMETRY_ALERTS,
    RELIABILITY_ALERT_CREATED: (
        TOPIC_TELEMETRY_ALERTS
    ),
    ALERT_CREATED: TOPIC_TELEMETRY_ALERTS,

    # Audit events
    AUDIT_EVENT_CREATED: TOPIC_AUDIT_EVENTS,

    # Incident events
    INCIDENT_CREATED: TOPIC_INCIDENT_EVENTS,
    RCA_COMPLETED: TOPIC_INCIDENT_EVENTS,

    # Chaos events and results
    CHAOS_EXPERIMENT_CREATED: TOPIC_CHAOS_EVENTS,
    CHAOS_RUN_STARTED: TOPIC_CHAOS_EVENTS,
    CHAOS_FAULT_INJECTED: TOPIC_CHAOS_EVENTS,
    CHAOS_OBSERVATION_RECORDED: TOPIC_CHAOS_EVENTS,
    CHAOS_RUN_COMPLETED: TOPIC_CHAOS_RESULTS,
    CHAOS_RUN_FAILED: TOPIC_CHAOS_RESULTS,
    CHAOS_RUN_ABORTED: TOPIC_CHAOS_RESULTS,
    EXPERIMENT_BENCHMARK_CALCULATED: TOPIC_CHAOS_RESULTS,

    # Remediation events
    REMEDIATION_RECOMMENDED: TOPIC_REMEDIATION_EVENTS,
    REMEDIATION_APPROVED: TOPIC_REMEDIATION_EVENTS,
    REMEDIATION_REJECTED: TOPIC_REMEDIATION_EVENTS,
    REMEDIATION_COMMAND_CREATED: (
        TOPIC_REMEDIATION_COMMANDS
    ),
    REMEDIATION_COMPLETED: TOPIC_REMEDIATION_RESULTS,
    REMEDIATION_FAILED: TOPIC_REMEDIATION_RESULTS,
    ROLLBACK_STARTED: TOPIC_REMEDIATION_COMMANDS,
    ROLLBACK_COMPLETED: TOPIC_REMEDIATION_RESULTS,
    RECOVERY_VERIFIED: TOPIC_REMEDIATION_RESULTS,
    RECOVERY_FAILED: TOPIC_REMEDIATION_RESULTS,
}