SCHEMA_VERSION = "1.0"

# Kafka topics
TOPIC_PIPELINE_EVENTS = "pipeline.events"
TOPIC_DEPLOYMENT_EVENTS = "deployment.events"
TOPIC_KUBERNETES_EVENTS = "kubernetes.events"
TOPIC_TELEMETRY_ALERTS = "telemetry.alerts"
TOPIC_INCIDENT_EVENTS = "incident.events"
TOPIC_REMEDIATION_COMMANDS = "remediation.commands"
TOPIC_REMEDIATION_RESULTS = "remediation.results"
TOPIC_AUDIT_EVENTS = "audit.events"
TOPIC_DEAD_LETTER_EVENTS = "dead-letter.events"


# Pipeline events
PIPELINE_STARTED = "PIPELINE_STARTED"
PIPELINE_COMPLETED = "PIPELINE_COMPLETED"
PIPELINE_FAILED = "PIPELINE_FAILED"
PIPELINE_RISK_CALCULATED = "PIPELINE_RISK_CALCULATED"
PIPELINE_SECURITY_SCAN_COMPLETED = "PIPELINE_SECURITY_SCAN_COMPLETED"


# Release / deployment events
RELEASE_APPROVED = "RELEASE_APPROVED"
DEPLOYMENT_STARTED = "DEPLOYMENT_STARTED"
DEPLOYMENT_COMPLETED = "DEPLOYMENT_COMPLETED"
DEPLOYMENT_FAILED = "DEPLOYMENT_FAILED"


# Kubernetes events
KUBERNETES_DEPLOYMENT_HEALTHY = "KUBERNETES_DEPLOYMENT_HEALTHY"
KUBERNETES_DEPLOYMENT_UNHEALTHY = "KUBERNETES_DEPLOYMENT_UNHEALTHY"
KUBERNETES_POD_UNHEALTHY = "KUBERNETES_POD_UNHEALTHY"
KUBERNETES_RESTART_DETECTED = "KUBERNETES_RESTART_DETECTED"
KUBERNETES_ROLLOUT_FAILED = "KUBERNETES_ROLLOUT_FAILED"


# Observability alert events
HIGH_ERROR_RATE = "HIGH_ERROR_RATE"
HIGH_LATENCY = "HIGH_LATENCY"
POD_RESTART_SPIKE = "POD_RESTART_SPIKE"
SERVICE_DEGRADED = "SERVICE_DEGRADED"
SERVICE_DOWN = "SERVICE_DOWN"


# Audit / incident / remediation events
AUDIT_EVENT_CREATED = "AUDIT_EVENT_CREATED"
INCIDENT_CREATED = "INCIDENT_CREATED"
REMEDIATION_COMMAND_CREATED = "REMEDIATION_COMMAND_CREATED"
REMEDIATION_COMPLETED = "REMEDIATION_COMPLETED"
REMEDIATION_FAILED = "REMEDIATION_FAILED"


EVENT_TOPIC_MAP = {
    # Pipeline events
    PIPELINE_STARTED: TOPIC_PIPELINE_EVENTS,
    PIPELINE_COMPLETED: TOPIC_PIPELINE_EVENTS,
    PIPELINE_FAILED: TOPIC_PIPELINE_EVENTS,
    PIPELINE_RISK_CALCULATED: TOPIC_PIPELINE_EVENTS,
    PIPELINE_SECURITY_SCAN_COMPLETED: TOPIC_PIPELINE_EVENTS,

    # Deployment events
    RELEASE_APPROVED: TOPIC_DEPLOYMENT_EVENTS,
    DEPLOYMENT_STARTED: TOPIC_DEPLOYMENT_EVENTS,
    DEPLOYMENT_COMPLETED: TOPIC_DEPLOYMENT_EVENTS,
    DEPLOYMENT_FAILED: TOPIC_DEPLOYMENT_EVENTS,

    # Kubernetes events
    KUBERNETES_DEPLOYMENT_HEALTHY: TOPIC_KUBERNETES_EVENTS,
    KUBERNETES_DEPLOYMENT_UNHEALTHY: TOPIC_KUBERNETES_EVENTS,
    KUBERNETES_POD_UNHEALTHY: TOPIC_KUBERNETES_EVENTS,
    KUBERNETES_RESTART_DETECTED: TOPIC_KUBERNETES_EVENTS,
    KUBERNETES_ROLLOUT_FAILED: TOPIC_KUBERNETES_EVENTS,

    # Observability alert events
    HIGH_ERROR_RATE: TOPIC_TELEMETRY_ALERTS,
    HIGH_LATENCY: TOPIC_TELEMETRY_ALERTS,
    POD_RESTART_SPIKE: TOPIC_TELEMETRY_ALERTS,
    SERVICE_DEGRADED: TOPIC_TELEMETRY_ALERTS,
    SERVICE_DOWN: TOPIC_TELEMETRY_ALERTS,

    # Audit / incident / remediation events
    AUDIT_EVENT_CREATED: TOPIC_AUDIT_EVENTS,
    INCIDENT_CREATED: TOPIC_INCIDENT_EVENTS,
    REMEDIATION_COMMAND_CREATED: TOPIC_REMEDIATION_COMMANDS,
    REMEDIATION_COMPLETED: TOPIC_REMEDIATION_RESULTS,
    REMEDIATION_FAILED: TOPIC_REMEDIATION_RESULTS,
}